### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by erikb85** [shurcooL/eX0#1]
Seen your comment on the 2d lightning HN article. This code is not really open source yet, though. You might consider putting a license here.

My suggestion is Apache or MIT license if you don't mind what others do with it, and GPLv3+ if you try to make others open their changes to your code as well.

**Comment by shurcooL** [comment]
> My suggestion is Apache or MIT license

I am using MIT license already, see [here](https://github.com/shurcooL/License). I'll make it more visible.

**Comment by erikb85** [comment]
Quoted from the MIT license as an example:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

So having it in an extra repo might not be enough.

**Comment by shurcooL** [comment]
I'll add it to README then.
