### ISSUE TITLE
Show some mistakes when I build the Project

### ISSUE THREAD

**Issue by Think-Jumper** [shurcooL/eX0#10]
Hi，I'm new in golang and learning you project，it's pretty interesting，but when I build you source code in project , it's show some mistakes such as like that:

```
# command-line-arguments
.\main.go:18: undefined: server
.\main.go:19: undefined: client
.\main.go:20: undefined: view
.\main.go:32: undefined: newClientNetwork
.\main.go:41: undefined: startClient
.\main.go:44: undefined: startServer
too many errors
```

I'm skilled in Unity'C# but not golang，Isn't I do something wrong？
My golang's version is 1.7 
I'm looking forward to your reply.

**Comment by shurcooL** [comment]
Hi, thanks.

What command(s) did you run?

**Comment by Think-Jumper** [comment]
I use the "go build main.go" in the proejct: eX0-go. 
Did I need to set the "go env"'s GOARCH=js? But when I set the GOARCH=js, there was show the error:"cmd/go: unsupported GOOS/GOARCH pair windows/js"

**Comment by shurcooL** [comment]
That's not the right command to use. Please see the installation section in the README of eX0-go folder:

https://github.com/shurcooL/eX0/tree/master/eX0-go#installation

**Comment by Think-Jumper** [comment]
Oh,I see.The way of your exe file is run as a command executable file.So when I use "go build",it already build finish actually.And "go build main.go" isn't right.
 I always think it as a normal exe file in a wrong way.....Thanks for you help! (~_~)

**Comment by shurcooL** [comment]
You're welcome, thanks for trying eX0!

Closing since your question is resolved.
