### ISSUE TITLE
How to get browser version up and running?

### ISSUE THREAD

**Issue by PaulCapestany** [shurcooL/eX0#5]
I saw the [r/golang](https://www.reddit.com/r/golang/comments/3gt6vm/tcpudpwebsocket_multiplayer_2d_game_in_go_with/) post about this project—thought this was super cool! 

I was able to get the normal Go server/clients working just fine, however I'm brand new to GopherJS and was wondering how it is that the JS is meant to be generated and then run?

**Comment by shurcooL** [comment]
Hey @PaulCapestany,

> I was able to get the normal Go server/clients working just fine

That's awesome! I will post instructions on how to get the browser client up and running shortly. It is super easy, but I need to document this.

Thanks for trying it out! :)

**Comment by shurcooL** [comment]
I've added [browser instructions to the README](https://github.com/shurcooL/eX0/tree/master/eX0-go#browser). Everything should go absolutely smoothly and take no more than a few minutes to have it running. Please let me know if that's not the case, if you run into any issues, or anything is unclear, so I can fix it.

**Comment by PaulCapestany** [comment]
Sweet—got it running in the browser, thanks! 

Just wanted to give a quick head's up though that it was also necessary to run `go get -u github.com/goxjs/websocket` and `go get -u github.com/gopherjs/websocket` in order to build the browser stuff… other than that, it went pretty absolutely smoothly indeed :)

**Comment by shurcooL** [comment]
Ah, yes. I mistakenly thought that dependency would be taken care of during the `go get -u -d -tags=js github.com/shurcooL/eX0/eX0-go` step from installation section, but I forgot that it's hidden behind the `tcp` build tag. I will fix this.

**Comment by shurcooL** [comment]
Ok, I've updated the instructions in 035c190adbf8cd143379bab455f5a96a26d05478 such that it should work on first try next time.

Thank you for testing and reporting the issue @PaulCapestany!
