### ISSUE TITLE
Dead blog link in README

### ISSUE THREAD

**Issue by binary132** [shurcooL/eX0#7]
I'd like to know how to make my networked game smooth as butter ;)

https://shurcool.wordpress.com/2011/07/25/how-to-make-your-networked-game-smooth-as-butter/

**Comment by shurcooL** [comment]
Hi @binary132,

Thanks for reporting this. I'm actually working on making my old blog available again. When I'm done, I'll update the link and let you know.

Thanks for your interest!

**Comment by shurcooL** [comment]
I've made my old blog content available again, and you can read that blog post here now:

https://dmitri.shuralyov.com/blog/10

Admittedly, the title was a little clickbait-y, but the post does explain a pretty cool networking insight/trick.
